# Generated by Django 5.1.4 on 2025-04-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0001_initial"),
        ("receipt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="document.document",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="receipt.vendor",
            ),
        ),
    ]
