# Generated by Django 5.1.4 on 2025-05-19 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt", "0002_alter_receipt_document_alter_receipt_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="total_expediture",
            new_name="total_expenditure",
        ),
    ]
