# Generated by Django 5.1.4 on 2025-05-22 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipt", "0003_alter_receipt_user_receiptimage_alter_receipt_image"),
        ("receipt", "0003_rename_total_expediture_receipt_total_expenditure"),
    ]

    operations = []
