# Generated by Django 5.2.1 on 2025-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipt", "0004_merge_20250523_0621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="category",
            field=models.CharField(
                choices=[
                    ("UTILITIES", "Utilities"),
                    ("FOOD", "Food"),
                    ("TRANSPORTATION", "Transportation"),
                    ("ENTERTAINMENT", "Entertainment"),
                    ("OTHER", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
