# Generated by Django 5.2.1 on 2025-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipt", "0005_alter_receipt_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="deductible_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="receipt",
            name="is_deductible",
            field=models.BooleanField(default=False),
        ),
    ]
