# Generated by Django 5.1.4 on 2025-02-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_chat_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="removed",
            field=models.BooleanField(default=False),
        ),
    ]
