name: CI workflow
on: push

jobs:
    run-format-checker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: pip install
              run: pip install black pre-commit

            - name: setup pre-commit hook
              run: pre-commit install

            - name: Lint code
              run: black . --check --verbose --diff --color
