# This workflow will install dependencies, create coverage tests and run Pytest Coverage Comment
# For more information see: https://github.com/MishaKav/pytest-coverage-comment/
name: pytest-coverage-comment
on:
  pull_request:
    branches:
      - '*'

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
# `contents` is for permission to the contents of the repository.
# `pull-requests` is for permission to pull request
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_python
      - uses: ./.github/actions/job_url
        id: job_url
        with:
          step_name: 'pytest'
      - name: pytest
        run: |
          pytest
      - name: Test coverage summary report
        id: coverage_report
        if: always()
        run: |
          {
            echo "COVERAGE_REPORT<<EOF"
            coverage report --format=markdown --show-missing --skip-covered
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Remove previous coverage comments
        uses: ./.github/actions/remove_comments
        if: always()
        with:
          identifier: coverage
      - name: Test coverage PR comment
        id: coverage_comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `[coverage](${{steps.job_url.outputs.job_url}})
              \r\n\r\n${{steps.coverage_report.outputs.COVERAGE_REPORT}}`
            })
